### ISSUE TITLE
Import URL in readme is a 404

### ISSUE THREAD

**Issue by brandonkal** [johnsonjo4531/read_lines#4]
There is no release tagged with that version here.

**Comment by johnsonjo4531** [comment]
@brandonkal I may have fixed the issue with the 404 but it appears there is a new issue with #5 . I'll have to get to this sometime later and I'm not exactly sure where the error is originating from as typescript doesn't give stack traces.

**Comment by johnsonjo4531** [comment]
Should be fixed now on the master branch and in v3.0.3
