### ISSUE TITLE
Error (TS2367) doesn't allow building and running

### ISSUE THREAD

**Issue by somerandomdev49** [johnsonjo4531/read_lines#7]
Here's the error: `error TS2367: This condition will always return 'true' since the types 'Uint8Array | undefined' and 'unique symbol' have no overlap.` I cant run my code because it fails to build :(

**Comment by johnsonjo4531** [comment]
Try using v3.0.3. It should hopefully fix any difficulties I made with changing the libraries dependencies to not be pinned. Also if you are using this library for just the lines part I would suggest that you try using the deno std libraries' `readLines` module in std/io/bufio.ts which should now do the exact same thing. `readLines`' usage is outlined here: https://github.com/denoland/deno/issues/1805#issuecomment-592952239. Let me know if that helps and feel free to close this this issue if it did or ask for me help if it didn't.

**Comment by somerandomdev49** [comment]
Thanks! It worked!
